# URL du serveur SonarQube (surcharger via -Dsonar.host.url si besoin)
sonar.host.url=http://localhost:9000

# Identification du projet
sonar.projectKey=micode
sonar.projectName=Micode
sonar.projectVersion=0.0.1-SNAPSHOT

# Sources
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Encodage
sonar.sourceEncoding=UTF-8

# Exclusions (code general migrations SQL)
sonar.exclusions=**/MicodeApplication.java,**/db/migration/**

# Couverture de tests
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/config/**,**/model/**,**/dto/**,**/MicodeApplication.java

# Quality Gate
sonar.qualitygate.wait=true

# Rapports
sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
sonar.java.spotbugs.reportPaths=target/spotbugsXml.xml
